services:
  # Apps will go here
  # dashboard:
  #   build: ./apps/dashboard
  #   container_name: grund-dashboard
  #   ports:
  #     - '3000:3000'
  #   ...

networks:
  grund-network:
    external: false