import type { BriefEmail, GeneratedBrief } from './types'
import { SECTION_CONFIG } from './types'

interface RendererOptions {
  anthropicBaseUrl: string
  anthropicApiKey: string
}

const BRIEF_SYSTEM_PROMPT = `You are generating a daily email brief — a beautiful, scannable summary of non-urgent emails.

You will receive a structured list of emails grouped by category. Generate an HTML email body that is:
- Scannable in 30 seconds
- Clean, minimal design with good whitespace
- Mobile-friendly (single column, max-width 600px)
- Uses inline CSS only (no <style> blocks — email clients strip them)

For each section, write a 1-sentence summary of the theme or highlights, then list individual emails as compact items showing sender and subject.

If a section has many similar emails (e.g. 10 GitHub notifications), group them into a single line like "10 GitHub notifications (repo-x, repo-y)".

Do NOT include <html>, <head>, or <body> tags — just the inner content that goes inside the email body.
Output only the HTML, no commentary.`

/**
 * Use Claude to generate a beautiful HTML brief from collected emails.
 */
export async function renderBrief(
  emails: BriefEmail[],
  periodStart: Date,
  periodEnd: Date,
  opts: RendererOptions,
): Promise<GeneratedBrief> {
  const isMorning = periodEnd.getHours() < 14
  const briefType = isMorning ? 'Morning' : 'Afternoon'
  const dateStr = periodEnd.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  })

  // Group emails by category
  const grouped = new Map<string, BriefEmail[]>()
  for (const email of emails) {
    const list = grouped.get(email.category) ?? []
    list.push(email)
    grouped.set(email.category, list)
  }

  // Build structured input for Claude
  const sections: string[] = []
  for (const [category, config] of Object.entries(SECTION_CONFIG)) {
    const categoryEmails = grouped.get(category)
    if (!categoryEmails?.length) continue

    const emailLines = categoryEmails.map(
      (e) => `  - From: ${e.fromAddress} | Subject: ${e.subject}`,
    )
    sections.push(
      `${config.icon} ${config.title} (${categoryEmails.length}):\n${emailLines.join('\n')}`,
    )
  }

  if (sections.length === 0) {
    return {
      subject: `${briefType} Brief: ${dateStr}, Inbox Zero 🎉`,
      htmlBody: renderEmptyBrief(briefType, dateStr),
      emailCount: 0,
      periodStart,
      periodEnd,
    }
  }

  const userMessage = [
    `Generate the ${briefType} Brief for ${dateStr}.`,
    `Period: ${periodStart.toLocaleTimeString()} – ${periodEnd.toLocaleTimeString()}`,
    `Total emails: ${emails.length}`,
    '',
    ...sections,
  ].join('\n')

  const res = await fetch(`${opts.anthropicBaseUrl}/v1/messages`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': opts.anthropicApiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: process.env.BRIEF_MODEL || 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      system: BRIEF_SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userMessage }],
    }),
  })

  if (!res.ok) {
    throw new Error(`Anthropic API error: ${res.status} ${await res.text()}`)
  }

  const data = (await res.json()) as {
    content: { type: string; text?: string }[]
  }

  const htmlBody = data.content.find((c) => c.type === 'text')?.text ?? ''

  return {
    subject: `${briefType} Brief: ${dateStr}, ${emails.length} ${emails.length === 1 ? 'email' : 'emails'}`,
    htmlBody: wrapBriefHtml(htmlBody, briefType, dateStr),
    emailCount: emails.length,
    periodStart,
    periodEnd,
  }
}

function wrapBriefHtml(innerHtml: string, briefType: string, dateStr: string): string {
  return `<div style="max-width:600px;margin:0 auto;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;padding:20px;">
  <div style="border-bottom:2px solid #e5e5e5;padding-bottom:16px;margin-bottom:24px;">
    <h1 style="margin:0;font-size:22px;font-weight:600;">${briefType} Brief</h1>
    <p style="margin:4px 0 0;font-size:14px;color:#666;">${dateStr}</p>
  </div>
  ${innerHtml}
  <div style="border-top:1px solid #e5e5e5;padding-top:16px;margin-top:32px;font-size:12px;color:#999;text-align:center;">
    Generated by Grund Email Triage · Emails that need your attention stay in your inbox
  </div>
</div>`
}

function renderEmptyBrief(briefType: string, dateStr: string): string {
  return wrapBriefHtml(
    `<div style="text-align:center;padding:40px 0;">
      <p style="font-size:48px;margin:0;">🎉</p>
      <p style="font-size:18px;font-weight:500;margin:12px 0 4px;">Nothing to report</p>
      <p style="font-size:14px;color:#666;margin:0;">No non-urgent emails since last brief. Enjoy the calm.</p>
    </div>`,
    briefType,
    dateStr,
  )
}
