import type { BriefEmail, GeneratedBrief } from './types'
import { SECTION_CONFIG } from './types'

export function renderBrief(
  emails: BriefEmail[],
  periodStart: Date,
  periodEnd: Date,
): GeneratedBrief {
  const isMorning = periodEnd.getHours() < 14
  const briefType = isMorning ? 'Morning' : 'Afternoon'
  const dateStr = periodEnd.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  })

  const subject = `${briefType} Brief — ${dateStr} — ${emails.length} ${emails.length === 1 ? 'email' : 'emails'}`

  const grouped = new Map<string, BriefEmail[]>()
  for (const email of emails) {
    const list = grouped.get(email.category) ?? []
    list.push(email)
    grouped.set(email.category, list)
  }

  const lines: string[] = [
    `${briefType} Brief`,
    dateStr,
    `${periodStart.toLocaleTimeString()} – ${periodEnd.toLocaleTimeString()}`,
    '',
  ]

  for (const [category, config] of Object.entries(SECTION_CONFIG)) {
    const categoryEmails = grouped.get(category)
    if (!categoryEmails?.length) continue

    lines.push(`${config.icon} ${config.title} (${categoryEmails.length})`)
    lines.push('-'.repeat(40))
    for (const e of categoryEmails) {
      lines.push(`  ${e.fromAddress}`)
      lines.push(`  ${e.subject}`)
      lines.push('')
    }
  }

  lines.push('—')
  lines.push('Generated by Grund Email Triage')

  return {
    subject,
    body: lines.join('\n'),
    emailCount: emails.length,
    periodStart,
    periodEnd,
  }
}
