import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { ScoredIdea } from './types.js';
import { SCORING_WEIGHTS } from './types.js';

const OUTPUT_DIR = path.join(import.meta.dirname, '../output');
const RECOMMENDATIONS_FILE = path.join(OUTPUT_DIR, 'recommendations.md');

function formatDate(dateStr: string): string {
  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(amount);
}

function getScoreEmoji(score: number): string {
  if (score >= 80) return '🟢';
  if (score >= 60) return '🟡';
  return '🟠';
}

function formatIdea(idea: ScoredIdea, rank: number): string {
  const emoji = getScoreEmoji(idea.score);

  return `### ${rank}. ${idea.name} ${emoji}

**Score: ${idea.score}/100** | ${idea.model_type} | ${idea.revenue_type} revenue

${idea.rationale}

| Metric | Value | Score |
|--------|-------|-------|
| Capital Required | ${formatCurrency(idea.capital_required_estimate)} | ${idea.score_breakdown.capital}/10 |
| Time to Revenue | ${idea.time_to_first_revenue_days} days | ${idea.score_breakdown.time_to_revenue}/10 |
| Revenue Type | ${idea.revenue_type} | ${idea.score_breakdown.revenue_type}/10 |
| Location | ${idea.location_dependent ? 'Dependent' : 'Flexible'} | ${idea.score_breakdown.location}/10 |
| Complexity | ${idea.decision_complexity} | ${idea.score_breakdown.complexity}/10 |

📰 [Source](${idea.source_url}) (${formatDate(idea.source_date)})

---
`;
}

export function generateMarkdown(ideas: ScoredIdea[]): string {
  const timestamp = new Date().toISOString();
  const topIdeas = ideas.slice(0, 20); // Top 20 recommendations

  const sections = [
    `# Business Opportunity Recommendations

*Generated: ${formatDate(timestamp)}*

Analysis of ${ideas.length} business ideas from Chris Koerner's newsletter, scored against your criteria.

## Scoring Criteria

| Factor | Weight | Preference |
|--------|--------|------------|
| Time to First Revenue | ${SCORING_WEIGHTS.time_to_revenue} | <90 days |
| Capital Required | ${SCORING_WEIGHTS.capital} | <$10K |
| Decision Complexity | ${SCORING_WEIGHTS.complexity} | Low (AI-assistable) |
| Revenue Type | ${SCORING_WEIGHTS.revenue_type} | Recurring |
| Location | ${SCORING_WEIGHTS.location} | Flexible or Bay Area |

**Required filters:** Physical-world business, Solo-operable (no W-2 employees)

---

## Top Recommendations

`,
  ];

  topIdeas.forEach((idea, index) => {
    sections.push(formatIdea(idea, index + 1));
  });

  // Summary stats
  const avgScore = Math.round(ideas.reduce((sum, i) => sum + i.score, 0) / ideas.length);
  const modelTypes = ideas.reduce(
    (acc, i) => {
      acc[i.model_type] = (acc[i.model_type] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );

  sections.push(`
## Summary Statistics

- **Total Ideas Analyzed:** ${ideas.length}
- **Average Score:** ${avgScore}/100
- **Top Score:** ${ideas[0]?.score || 0}/100

### By Business Model
${Object.entries(modelTypes)
  .sort((a, b) => b[1] - a[1])
  .map(([type, count]) => `- ${type}: ${count}`)
  .join('\n')}

---

*This analysis was generated by the Grund Newsletter Analyzer. Ideas are extracted from [Chris Koerner's Newsletter](https://newsletter.chrisjkoerner.com/).*
`);

  return sections.join('\n');
}

export async function writeRecommendations(ideas: ScoredIdea[]): Promise<string> {
  const markdown = generateMarkdown(ideas);
  await writeFile(RECOMMENDATIONS_FILE, markdown);
  console.log(`Recommendations written to ${RECOMMENDATIONS_FILE}`);
  return RECOMMENDATIONS_FILE;
}
